### ISSUE TITLE
Review Governance written material

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/2024-rcm-rpm-tasks#14]

**Comment by AlexandraAAJ** [comment]
On Monday 29 January we will send the two articles to Malvika, for her review prior to upload as a PR

**Comment by aleesteele** [comment]
@AlexandraAAJ and @aleesteele to send to MS for review by 31 of January.

**Comment by aleesteele** [comment]
Closing this as the other piece is currently being reviewed!
