### ISSUE TITLE
TTW PH 2024 Plan

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/2024-rcm-rpm-tasks#2]

**Comment by AlexandraAAJ** [comment]
On 18 January, there's an in-person meeting with Innovate UK (founder of BridgeAI) to review The Turing Way Practitioners Hub for 2024 plan. The presentation should include:
- Intro of TTW and TTW PH
- Learnings and outputs from first cohort, qualitative data
- 2024 Plan
- BridgeAI and TTWPH opportunities for collaboration: Open Source and AI, find their ideas to connect with SME's. Where is an opportunity and knowledge gap?

**Comment by AlexandraAAJ** [comment]
- Plans for 2024 approved by KW and MS: https://hackmd.io/Iy4meKqFRuuG3E6mGQ6ohg
- Presentation WIP here: https://docs.google.com/presentation/d/16X3b2vpUIb_mCIUu7xUkaHg1W6T5u38-/edit#slide=id.g1f9b174de22_2_2655

**Comment by aleesteele** [comment]
Good luck with your presentation @AlexandraAAJ !

**Comment by AlexandraAAJ** [comment]
Presentation went very well, will mark this task as done!

**Comment by AlexandraAAJ** [comment]
- Archive the plan and follow up the actions at the TTW Repo

**Comment by aleesteele** [comment]
Should we close & archive this @AlexandraAAJ ?
