### ISSUE TITLE
Start the Expression of Interest for the 2nd Cohort of TTWPH

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/2024-rcm-rpm-tasks#27]

**Comment by AlexandraAAJ** [comment]
[The Turing Way Practitioners Hub](https://www.turing.ac.uk/turing-way-practitioners-hub) has successfully finished their first cohort and a new EoI will be launched. 

Draft is available here: https://thealanturininstitute.sharepoint.com/:w:/r/sites/InnovateUKlinks/_layouts/15/Doc.aspx?sourcedoc=%7B90E69F30-4709-45FF-A972-9BC2893117B4%7D&file=EoI%20TTW%20PH%20Cohort%202%20Feb2024.docx&nav=eyJjIjo3NjM0ODk3OTR9&action=default&mobileredirect=true

- [ ] Feedback from Dominica and Arielle
- [ ] Combined feedback and share it with KW
- [ ] By 16 Feb, get Kirstie's feedback
- [ ] Send the EoI to BridgeAI (Grace and Victoria Bekham)

**Comment by AlexandraAAJ** [comment]
The form is now available here: https://forms.office.com/e/nk4kXZ2Fnt

- [ ] upload it in our website
- [ ] upload it in our start page @aleesteele 
- [ ] promote it in the next Newsletters, the form will open till 31 May 2024

**Comment by aleesteele** [comment]
Now on social media:
https://twitter.com/turingway/status/1775096223055098295
https://www.linkedin.com/feed/update/urn:li:activity:7180861888291860480
https://fosstodon.org/@turingway/112200958328548589

**Comment by aleesteele** [comment]
Closing this for now!
