### ISSUE TITLE
TTW PH Comms Campaign

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/2024-rcm-rpm-tasks#3]

**Comment by AlexandraAAJ** [comment]
Based on this https://docs.google.com/document/d/1yV2Gth7ANRq5MiLB-dFPDKIwqD5ZC2U7/edit#heading=h.gjdgxs

Work on:
- [ ] 1-pager per case study, connecting the highlights and Fireside Chat video about AI adoption
- [ ] Confirm with Izzy if the promotion dates make sense or if she recommends to promote all the case studies together 
- [ ] BridgeAI: approve the Case study Branding template: [Comm External TTWPH - Google Drive](https://drive.google.com/drive/u/0/folders/13KPX43L87fLDToeh0id_H_-o80dWdDWa)
- [ ] Add the copy that will go with each post and the partner’s social media details
- [ ] Finish the 1-pager format with our designer and have everything available one week 
- [ ] Share the plan with the Experts in residence 
- [ ] Promote them as the plan

**Comment by aleesteele** [comment]
Closing this as completed for now – let me know if this is okay @AlexandraAAJ 😄
