### ISSUE TITLE
[ONBOARDING] Léllé Demertzi - RPM

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/2024-rcm-rpm-tasks#46]
# Welcome, Léllé! :sun_with_face: 

Onboarding check-list for TPS: https://github.com/alan-turing-institute/tps-project-management

Notes/Turing Specific for Léllé

Project board: https://github.com/orgs/the-turing-way/projects/3/views/2

- Onboarding notes 
    - General IT: https://hackmd.io/@cm-team/onboarding (taken from Malvika)
- Turing Acronyms: https://thealanturininstitute.sharepoint.com/:w:/s/rid/ESfeWchNrgVHnUdqFlNoFtEBcsCJqHya-oOjN1ixCVkNBQ?e=xBilWc
- TPS RACI Matrix: https://thealanturininstitute.sharepoint.com/:x:/s/rid/EUnS3TZcbCtOhX6RiqcZSuMB_1e8gNtYUvs_pLaOa3vHrg?e=YddofX

# TTW Core Team Onboarding checklist
This was copied from the broader core team onboarding packet, for your own reference: https://hackmd.io/@turingway/ttw-core-team-onboarding :sunflower: 

## Accounts and Permissions
- [x] Add to [TTW Github repository](https://github.com/alan-turing-institute/the-turing-way) with "Writer" permissions (change as needed for role)
- [x] Add to [Ways of Working](https://github.com/alan-turing-institute/the-turing-way/blob/main/ways_of_working.md) page on TTW Github repository 
- [ ] ~Add to [Core Team Google group](https://groups.google.com/u/1/g/core-team-2022) (currently dormant)~
- [ ] (If applicable) Give Accounts/Password Access on Keybase
- [x] (If applicable) Add directly to [The Turing Way Core Google Drive](https://drive.google.com/drive/u/0/folders/1bdjA-fBotMi9CnjDqu84d5hPZWwjgi-x)
    - [x] Share [promotion pack](https://drive.google.com/drive/u/1/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF) folder
    - [x] Share [conference talks/workshop applications](https://drive.google.com/drive/u/0/folders/1eNHq9sXq6Z8Q5Ep0MzNS0GsB3FKgTi3E) folder
- [x] #47
- [ ] ~(If applicable) Add to Canva team~ @LelleDemertzi will talk to IT about getting access to Keybase
- [ ] (If applicable) Add to Penpot team
- [x] (If applicable) Add to HackMD team
- [x] (If applicable) Add to Keybase group @LelleDemertzi will talk to IT about getting access to Keybase

## About yourself
- [ ] Add information to [TTW Team slides](https://docs.google.com/presentation/d/1PeQ_gg5tOJVhOA4aSnVumsowD-bfRFEroWfGsxxaGCw/edit#slide=id.g1aee8e18598_0_0)
- [x] (If applicable) add yourself to [TTW project page](https://www.turing.ac.uk/research/research-projects/turing-way) on Alan Turing website
- [x] (If applicable) add yourself to [TPS/Whitaker Lab slide deck](https://docs.google.com/presentation/d/1g-plncmi00FK97QuYDfqq7oPzUmL0xkHm1hy4X81IX8/edit#slide=id.gf5e62e1b31_1_0)
- [ ] Introduce yourself on the Turing Way slack (in #introductions)

## Events & Calendars

- [ ] Give links to TTW Community Calendars
    - [ ] The Turing Way Community (public-facing)
    - [x] The Turing Way Core Team (internal)
- [x] Add to calendar invites for The Turing Way core team
    - [x] Coworking Calls
    - [x] Collaboration Cafes
    - [x] Fireside Chat
    - [x] Community Chats

## Communication Channels + Platforms
- [x] Share links
    - [x] [Slack](https://theturingway.slack.com/)
    - [x] [Twitter](https://twitter.com/turingway)
    - [x] Mastodon
    - [x] Newsletter
- [x] Useful Links/Information Hub
    - [x] [Core Team note of notes](https://hackmd.io/@turingway/ttw-team-note-of-notes)

If applicable, see [TPS Project Management Repository](https://github.com/alan-turing-institute/tps-project-management) about being onboarded onto the Tools, Practices, and Systems programme more broadly at the Alan Turing Institute. Other research teams and/or groups may have their own onboarding practices and/or repositories (i.e. the [Research Application Manager (RAM) team](https://github.com/alan-turing-institute/research-application-management) or [Community Management (CM) team](https://github.com/alan-turing-institute/open-community-building)).

## Useful links
- [The Turing Way Core Google Drive](https://drive.google.com/drive/u/0/folders/1bdjA-fBotMi9CnjDqu84d5hPZWwjgi-x)
- [Community Handbook](https://the-turing-way.netlify.app/community-handbook/community-handbook.html)
- [TTW Guide to Using Slack](https://hackmd.io/@turingway/ttw-slack-intro)
- [TTW Github repository guide](https://docs.google.com/spreadsheets/d/19IfeIxtWQpDglzfOY8vpq6TFhM1jEJa1OnNdAYWjzg8/edit#gid=1136871433)
- [TTW Translation Github team](https://github.com/TWTranslation)
- TTW Core Team Google Drive Guide

## TTW-PM specific tasks:
- Existing Project Management
    - Github: https://github.com/orgs/alan-turing-institute/projects/27/views/1 - Is this project board out of date?
    - Trello: https://trello.com/b/F1nERwsT/community-management
    - Note of notes: https://hackmd.io/@turingway/ttw-team-note-of-notes
- Turing Way Core: https://drive.google.com/drive/folders/1bdjA-fBotMi9CnjDqu84d5hPZWwjgi-x
- Templates & Walk-through
    - [Newsletter](https://hackmd.io/Ll90z3ttQMm4voOBZV503A?both)
    - Fireside chat planning
        - Invitation emails
        - Planning document
        - Follow-up emails (reminder week before)
    - Workshop/Conference Planning
        - Workshop document (with timings)
        - Exhibit planning (for gear)
    - Communications slide deck
    - Partners & Community
- Onboarding tasks: https://hackmd.io/@cm-team/onboarding
- Checklists
    - Before/During/After Fireside
    - Before/During/After Book Dash
    - Before/During/After Collab Cafe
    - Before/During/After Coworking call
    - Before/During/After Core Team Meeting

**Comment by aleesteele** [comment]
# 16 September

**Comment by aleesteele** [comment]
@Arielle-Bennett - I've sent @LelleDemertzi the link for the TPS Project Management repository, wasn't sure if she should do any things there, but I know it was used for onboarding @AlexandraAAJ!

**Comment by aleesteele** [comment]
Join us in welcoming our New Research Project Manager, Léllé Demertzi!

We are delighted to announce that Léllé Demertzi has joined our team as the Research Project Manager of The Turing Way!

Léllé, a performance artist by training, brings a wealth of experience to The Turing Way community through her diverse roles and accomplishments.
Before joining our team, she served as a Programme Administrator for the Living with Machines project, where she helped organise various events, exhibitions, and outreach activities within the Arts and Humanities field.

Léllé also worked as the Programme Coordinator for Data Science for Science and Humanities and co-organised the AI & Arts Interest Group at The Alan Turing Institute.
We are excited to welcome her to our team and look forward to introducing her to our community!

**Comment by LelleDi** [comment]
* Newsletter ready to send out by EOD
* Introduction to Slack channels ready 
* For next meeting:
- Zenodo upload

**Comment by LelleDi** [comment]
Question RE: Turing reporting for Apr-Oct 2024

Where is information captured? Is there a process in place for formatting for the reporting template?

deadline 18/10/24

**Comment by Arielle-Bennett** [comment]
@aleesteele the repo we've moved to is tps-team, Léllé should have access to that now. Thanks!

**Comment by aleesteele** [comment]
Closing this - woohoo! 🙏

**Comment by AlexandraAAJ** [comment]
[celebrate]     Alexandra Araujo Alvarez reacted to your message:
________________________________
