### ISSUE TITLE
Book Dash Nov23 report

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/2024-rcm-rpm-tasks#6]

**Comment by aleesteele** [comment]
Discussed report at Coworking Call on Monday, 15 January with @EKaroune, @BatoolMM, @AlexandraAAJ

**Comment by BatoolMM** [comment]
Just dropping a note to say that I managed to finish off my section - give eme a shout if anything is missing!

**Comment by aleesteele** [comment]
Tied to #https://github.com/the-turing-way/the-turing-way/pull/3503
